### ISSUE TITLE
"Notes, Personality, NPCs, etc." tab not working under Firefox

### ISSUE THREAD

**Issue by baldurmen** [derikb/character-sheet-app#102]
Hi,
It seems the `4.0.0` release broke the "Notes, Personality, NPCs, etc." tab on Firefox. I'm running 96.0.3 and I consider it a relatively modern browser :)
Cheers,

**Comment by derikb** [comment]
@baldurmen Ohhh hmm. No errors just... nothing happens. I'll take a look tomorrow. Don't usually have these sort of things between chrome and ff.
