### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by AudreyNakoff** [derikb/character-sheet-app#103]
I have been using the site for my character for a 5e campaign. It was working great, and then when I pulled it up the other day, it was blank and I had to re-enter everything. I tried to login with my google account, so hopefully it could save it through that, but nothing happened when I clicked the button.

**Comment by derikb** [comment]
@AudreyNakoff Sorry you had some issues.  (fwiw, I hope you made backups as noted in the help text, before I added the sync function I made a backup of my character after every session just to be safe.)

For future reference, when reporting software issues it always helps to be as explicit as possible with what happened, else people trying to figure out the issue have to make assumptions or ask lots of follow-up questions.

So when you say "it was blank" I'm assuming you mean the character sheet came up but you had no characters to load? Local storage in the browser is not a permanent storage solution (at least not permanent in the sense anything on a computer is permanent). So it is possible for some reason your browser cleared all its storage info for the site (that could happen if you did a complete reinstall of the browser or did a history/info/cache clear of all your data or just the site's data in particular.

When you say you tried to login with Google, I'm assuming you haven't done that before.... I'm not sure which button you are referring to. Did you even get to the Google login screen at all?

I did notice the other day, that for reasons I haven't totally clarified (something in my server configs I need to clean up), you can actually load the character sheet app on multiple different subdomains. I'm wondering if you might have tried a different subdomain than where you last saved your character. The local storage is specific to a subdomain, so saving a character at character5e.derikbadman.com will not make it available at charsheet5e.derikbadman.com which can be confusing. I actually did that to myself the other day when I typed in the wrong domain and found no characters saved. So I would confirm the subdomains you are using.

https://charsheet5e.derikbadman.com is the 5e only version of the app.

https://charsheeet.derikbadman.com is the newer version (that will start supporting some other games).

That could also explain why the Google login didn't work (I'll need to look at improving the error handling/notices. As the connection to the syncing database is only allowed on the above two subdomains. So if you were on some other subdomain you may get the app, but Google would not allow you to authenticate.

For now that is my best guess.

**Comment by derikb** [comment]
Hi again @AudreyNakoff 

- I did a release to the new version of the app that improves error reporting for the auth code. Hopefully if issues still come up you'll see an error you can share.
- I fixed the issue where any old subdomain loaded the app, which _may have been causing issues/confusion.

I'm going to close this now, but let me know if you keep having errors.
