### ISSUE TITLE
Google login does not set the user correctly

### ISSUE THREAD

**Issue by NeptuneRjo** [derikb/character-sheet-app#120]
The Google Auth login returns no user after redirecting. Tested on Firefox and Chrome.

The fix is as simple as swapping to `signInWithPopup()` instead of using `signInWithRedirect()`, and I can put a PR up ASAP if that's an acceptable fix.

**Comment by derikb** [comment]
@NeptuneRjo uggh sorry about that. I was trying to fix that the other weekend by proxying the auth files but somethng wasn't working right (google's instructions are a little vague) and I never got back around to it. 

According to google's own docs the popup option may not work in some browsers either

https://firebase.google.com/docs/auth/web/redirect-best-practices is what i've been looking at.

**Comment by NeptuneRjo** [comment]
@derikb Strangely, popup's limitations are not mentioned in the docs for `signInWithPopup()`, but I see that now.

I'll take a look through https://firebase.google.com/docs/auth/web/redirect-best-practices and see if I can find any solutions

**Comment by derikb** [comment]
I think my test failed cause of some missing setting in the auth provider. Actually looking at it now to see if I can find where the redirect_uri is for the google auth.

I did get the proxying part work to serve the firebase files from my domain but the auth trip was not successful.

**Comment by derikb** [comment]
And now I'm wondering if my fix failed because of the service worker caching files and me not updating the versioning...

**Comment by derikb** [comment]
Ahh found the place for that setting

https://console.cloud.google.com/apis/credentials?project=[PROJECT NAME]

@NeptuneRjo Can you try now. You may have to reload once to get the new service worker.

**Comment by NeptuneRjo** [comment]
@derikb Silly question, are you following through 'Handle provider sign-in independently' or 'Proxy auth requests to firebaseapp.com'? I'm trying to understand Google's docs and I think im just confusing myself along the way lol

**Comment by derikb** [comment]
Woo hoo! Thanks for confirming and bringing this back to my attention, I had been working on it a few weeks ago and then got frustrated and gave up on it for awhile. (fwiw I am doing the proxy version, since I can edit my nginx configs.)

**Comment by derikb** [comment]
Closing. This works in production now. Nothing changed in the actual code it was all nginx, firebase config, and oauth provider settings changes.
