### ISSUE TITLE
Spell info modal

### ISSUE THREAD

**Issue by derikb** [derikb/character-sheet-app#123]
To add on to the spell add modal, we can maybe we up a way to show spell info too.

**Comment by NeptuneRjo** [comment]
I can take a look into this.

I think the easiest solution is to shift away from using the API and to just add the spell-data file from https://github.com/5e-bits/5e-database to this project.

No more need to rely on an API and this should give us more control over the data.

**Comment by derikb** [comment]
Now the trick is... linking the spell name in the list to the info about it. The current save just saves the spell as text and it remains editable no matter whether you typed it in or added via the modal.

Feels like the right thing to do is have some kind of key linking spells in the sheet to the spell data, but that creates its own issues of handling custom spells and spells not in the open license data. Not to mention causing issues with backwards compatible for existing saved data that has spell names listed.

We could save all the spell data in the sheet but that feels like a lot of extra info to save per characters, and I'm not totally sure at what point there is too much text/bytes for a single localStorage key (varies by browser).

I guess for now it could just be a level/title lookup. That's the path of least resistance.

**Comment by derikb** [comment]
fwiw @NeptuneRjo Tested the code from the PR and it seems to work fine to me. A couple things to think about:

1. its not at all clear you need to click the spell name area to see the spell info.
2. Clicking on add works, but it also doesn't _feel_ likes it doing anything. On my laptop I couldn't see the spell list behind the modal so until I closed it I had no idea the spell adding working. I wonder if its worth adding some kind of feedback to the UI.

**Comment by NeptuneRjo** [comment]
We can save only the parts of the spell that were used in the modal to minimize its size. This should make creating spell items for the saved-spells list easier.

Maybe with editable fields?
